### ISSUE TITLE
Flagged as a trojan virus

### ISSUE THREAD

**Issue by LIFEGOESON321** [skyworxx/NFCLoader#2]
This project was flagged by windows as having a known Trojan embedded in it?

**Comment by skyworxx** [comment]
This must be a false positive. I'm investigating. In the meantime you can build from source

**Comment by skyworxx** [comment]
I think the original project also contains a UDP server/receiver to send the ID of the NFC tag over the network. Windows might flag this is a trojan because it listens on the network and has the ability to start new apps

**Comment by skyworxx** [comment]
It might be because on top of trying to execute a new process (i.e. starting retroarch) it is also trying to get that window into the foreground. I ran the .exe through Microsoft Defender and it came back clean. I'll see if removing some of the functions that get the process into the foreground will calm the antivirus software

**Comment by skyworxx** [comment]
I have updated the code and added a new release. It downloads for me without issues and Defender also says it's clean.

I ran both old and new release through VirusTotal. The old release triggers 2 out of 72 AV providers and the one triggers only 1, which is "Trojan.Malware.300983.susgen" by MaxSecure. Googling that let me to others developers facing the same false positive issue.
